apiVersion: v1
kind: Service
metadata:
  name: corekube-worker
spec:
  ports:
  - name: worker-s1ap
    port: 5566
    targetPort: 5566
    protocol: UDP
  selector:
    app: corekube-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corekube-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corekube-worker
  template:
    metadata:
      labels:
        app: corekube-worker
    spec:
      containers:
      - name: corekube-worker
        image: ghcr.io/yutotakano/corekube5g-worker:latest
        ports:
        - containerPort: 5566
          protocol: UDP
          name: worker-s1ap
        command: ["./corekube_udp_worker", "$(THIS_POD_IP)", "$(COREKUBE_DB_SERVICE_HOST)", "6", "1", "$(CORE_METRICS_AGGREGATOR_SERVICE_HOST)"]
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 10m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: corekube-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corekube-worker
  minReplicas: 2
  maxReplicas: 200
  targetCPUUtilizationPercentage: 80


---


apiVersion: v1
kind: Service
metadata:
  name: corekube-db
spec:
  ports:
  - port: 7788
    targetPort: 7788
    protocol: TCP
  selector:
    app: corekube-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corekube-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corekube-db
  template:
    metadata:
      labels:
        app: corekube-db
    spec:
      containers:
      - name: corekube-db
        image: ghcr.io/yutotakano/corekube-db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7788
          protocol: TCP
        command: ["./corekubeDB", "$(THIS_POD_IP)"]
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: core-metrics-bus
spec:
  ports:
  - name: prometheus-scrape-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics-receive-port
    port: 7799
    targetPort: 7799
    protocol: TCP
  selector:
    app: core-metrics-bus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-metrics-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-metrics-bus
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
      labels:
        app: core-metrics-bus
    spec:
      containers:
      - name: core-metrics-bus
        image: ghcr.io/yutotakano/core_metrics_bus:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 7799
          protocol: TCP
        command: ["./core-metrics-bus"]
