# Create a deployment for a single cost model pod
#
# See environment variables if you would like to add a Prometheus for
# cost model to read from for full functionality.
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: opencost
#   labels:
#     app: opencost
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: opencost
#   strategy:
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
#     type: RollingUpdate
#   template:
#     metadata:
#       annotations:
#         prometheus.io/scrape: 'true'
#         prometheus.io/path: '/metrics'
#         prometheus.io/port: '9003'
#       labels:
#         app: opencost
#     spec:
#       restartPolicy: Always
#       serviceAccountName: opencost
#       containers:
#         - image: quay.io/kubecost1/kubecost-cost-model:latest
#           name: opencost
#           resources:
#             requests:
#               cpu: "10m"
#               memory: "55M"
#             limits:
#               cpu: "999m"
#               memory: "1G"
#           env:
#             - name: PROMETHEUS_SERVER_ENDPOINT
#               value: "http://corekube-prometheus.default.svc" # The endpoint should have the form http://<service-name>.<namespace-name>.svc
#             - name: CLOUD_PROVIDER_API_KEY
#               value: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U" # The GCP Pricing API requires a key. This is supplied just for evaluation.
#             - name: CLUSTER_ID
#               value: "cluster-one" # Default cluster ID to use if cluster_id is not set in Prometheus metrics.
#           imagePullPolicy: Always
#           securityContext:
#             allowPrivilegeEscalation: false
#             capabilities:
#               drop:
#                 - ALL
#             privileged: false
#             readOnlyRootFilesystem: true
#             runAsUser: 1001
#           # volumeMounts:
#           #   - name: cloud-integration
#           #     mountPath: /var/configs/cloud-integration
#         - image: quay.io/kubecost1/opencost-ui:latest
#           name: opencost-ui
#           resources:
#             requests:
#               cpu: "10m"
#               memory: "55M"
#             limits:
#               cpu: "999m"
#               memory: "1G"
#           imagePullPolicy: Always
#       # volumes:
#       #   - name: cloud-integration
#       #     secret:
#       #       secretName: opencost-csp-secret
#       #       items:
#       #         - key: cloud-integration.json
#       #           path: cloud-integration.json
#       ports:
#         - containerPort: 9003
#           hostPort: 9003
#           name: opencost
#         - containerPort: 9090
#           hostPort: 9090
#           name: opencost-ui
---

# # Expose UI externally
# kind: Service
# apiVersion: v1
# metadata:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: external
#     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#   name: kubecost
# spec:
#   selector:
#     app: kubecost
#   type: LoadBalancer
#   ports:
#     - name: opencost-ui
#       port: 9090
#       targetPort: 9090
# ---
