{
 "title": "CoreKube Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(coremon_ue_count_last_5_seconds, \"name\", \"Connected UEs\", \"\", \"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Estimated Number of Connected UEs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(coremon_ue_count_last_5_seconds, \"name\", \"UEs Seen in last 5 Seconds\", \"\", \"\")",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(amf_uplink_packets_total[$__rate_interval])), \"name\", \"Uplink Rate\", \"\", \"\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(sum(rate(amf_downlink_packets_total[$__rate_interval])), \"name\", \"Downlink Rate\", \"\", \"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(amf_downlink_packets_total[$__rate_interval])), \"name\", \"Downlink\", \"\", \"\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(sum(rate(amf_uplink_packets_total[$__rate_interval])), \"name\", \"Uplink\", \"\", \"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "si: cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(coremon_cpu_usage{namespace=\"default\", container_name!=\"corekube-core-monitor\"}), \"name\", \"CPU Total\", \"\", \"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CoreKube CPU Usage (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(coremon_cpu_usage{namespace=\"default\", container_name!=\"corekube-core-monitor\"}, \"name\", \"Worker $1\", \"pod_name\", \"corekube-worker-[^-]+-(.*)\"), \"name\", \"Frontend\", \"pod_name\", \"corekube-frontend-[^-]+-(.*)\"), \"name\", \"DB\", \"pod_name\", \"corekube-db-[^-]+-(.*)\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Breakdown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "si: cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(coremon_cpu_usage{namespace=\"default\", container_name=\"corekube-db\"}, \"name\", \"DB\", \"pod_name\", \"corekube-db-[^-]+-(.*)\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(coremon_cpu_usage{namespace=\"default\", container_name=\"corekube-frontend\"}, \"name\", \"Frontend\", \"pod_name\", \"corekube-frontend-[^-]+-(.*)\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(avg(coremon_cpu_usage{namespace=\"default\", container_name=\"corekube-worker\"}), \"name\", \"Worker Avg\", \"\", \"\")",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(sum(coremon_cpu_usage{namespace=\"default\", container_name=\"corekube-worker\"}), \"name\", \"Worker Total\", \"\", \"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(avg (amf_latency{nas_type!=\"0\"}), \"name\", \"Average Latency\", \"\", \"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latency (Core Internal)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(label_replace(label_replace(label_replace(label_replace(label_replace(label_replace(avg by(nas_type) (amf_latency{nas_type!=\"0\"}), \"name\", \"Registration Request\", \"nas_type\", \"65\"), \"name\", \"Registration Complete\", \"nas_type\", \"67\"), \"name\", \"Authentication\", \"nas_type\", \"87\"), \"name\", \"Registration Accept\", \"nas_type\", \"94\"), \"name\", \"5G PDU Session\", \"nas_type\", \"193\"), \"name\", \"Deregistration\", \"nas_type\", \"69\"))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(count(kube_pod_container_info{container=\"corekube-worker\"}), \"name\", \"Worker Count\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of CoreKube Workers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{container=\"corekube-worker\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Hourly Cost by Instance Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(node_total_hourly_cost) by (instance_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of EC2 Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count(node_total_hourly_cost{instance_type=\"c5.large\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(kubecost_pod_network_ingress_bytes_total{namespace=\"default\"}[$__rate_interval]) or rate(kubecost_pod_network_ingress_bytes_total{namespace=\"corekube-frontend\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(kubecost_pod_network_egress_bytes_total{namespace=\"default\"}[$__rate_interval]) or rate(kubecost_pod_network_egress_bytes_total{namespace=\"corekube-frontend\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost for last hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kubecost_cluster_management_cost) + sum(node_total_hourly_cost) + sum(kubecost_load_balancer_cost) + sum(kubecost_network_internet_egress_cost))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly Cluster Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "kubecost_cluster_management_cost",
     "legendFormat": "__auto"
    },
    { "expr": "node_total_hourly_cost", "legendFormat": "__auto" },
    { "expr": "kubecost_load_balancer_cost", "legendFormat": "__auto" },
    {
     "expr": "kubecost_network_internet_egress_cost",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "description": "Network traffic by pod",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total\n  {namespace!=\"\"}\n  [$__rate_interval])) \nby (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}<- in"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total\n  {namespace!=\"\"}\n  [$__rate_interval])) \nby (namespace, pod)",
     "legendFormat": "{{cluster_id}} {{namespace}}/{{pod}}-> out"
    }
   ]
  }
 ]
}