apiVersion: v1
kind: ConfigMap
metadata:
  name: corekube-prometheus-conf
  labels:
    name: corekube-prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
---
apiVersion: v1
kind: Service
metadata:
  name: corekube-prometheus
  labels:
    app: corekube-prometheus
spec:
  type: ClusterIP
  selector:
    app: corekube-prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: corekube-prometheus-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    app: corekube-prometheus
spec:
  # We have to use a LoadBalancer to get an external IP because the other options
  # cannot be used:
  # 1. ClusterIP: Not accessible from outside the cluster
  # 2. NodePort: Not available on Fargate, restricted to 30000-32767
  # 3. HostPort: Not available on Fargate
  type: LoadBalancer
  selector:
    app: corekube-prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corekube-prometheus
spec:
  selector:
    matchLabels:
      app: corekube-prometheus
  template:
    metadata:
      labels:
        app: corekube-prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.listen-address=0.0.0.0:9090"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: corekube-prometheus-config-volume
          mountPath: /etc/prometheus/
      volumes:
      - name: corekube-prometheus-config-volume
        configMap:
          name: corekube-prometheus-conf
